# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 465de79fec971ab39e41ec9db5e0dc37ebf6a172a74c2aa361872ee5ff950410d423b1fd746817a3e0e4c3504c79f1f8ec16ec668bfd561d29d198362eef2a9e

test:
  secret_key_base: 01b5b7bbdbf18f63ef5275372523ceb994886ab2761d0c656f1c3fbb5b15d5d04ea602f4e6046a699206b886a3c82cee4be40135f9452f74c6c197d9dd37d03a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
